# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Actuator configuaration
endpoints:
    actuator:
        enabled: false
    enabled: false

spring:
    application:
        name: spring-boot-web-skeleton
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
            # TODO: secure: true

info:
    project:
        version: #project.version#

documentation:
    title: spring-boot-web-skeleton API documentation
    description: Simple API documentation
    version: 0.0.1-SNAPSHPOT
    license: MIT License
    license-url: http://www.opensource.org/licenses/mit-license.php

token:
    expiration-time-in-minutes: 15

    # CHANGE THIS *SECRET KEY* FOR USE IN YOUR OWN APPLICATION!
    signing-key: 259A3EB7-B9CD-4FD7-A328-701EDF22EBC1 # used for signing and encryption

    # CHANGE THIS
    issuer: spring-boot-web-skeleton

web:
    http-version: 1.1 # HTTP/1.1
    cache-time-to-live-in-days: 1461 # 4 years

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationConfig class
# to have type-safe configuration, like in the sections above
# ===================================================================

application:
